title: The BytePath Chronicles
description: Blog t√©cnico de mis apuntes
theme: jekyll-theme-hacker
baseurl: /bytepath-blog  # Importante si tu repositorio no es <usuario>.github.io
# comentario para forzar la actualizacion

